services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booksapi-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=BooksDb;User Id=sa;Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True"
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booksapi-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "14333:1433"
    volumes:
      - booksapi_sql_data:/var/opt/mssql

volumes:
  booksapi_sql_data: