services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booksapi-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "14333:1433"
    volumes:
      - booksapi_sql_data:/var/opt/mssql

volumes:
  booksapi_sql_data: