name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore
        working-directory: ./BooksAPIDapper

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./BooksAPIDapper

      # Remove this step if you don't have tests yet
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./BooksAPIDapper
